baseurl                  = "https://pelegri.netlify.com"           # Your domain name. Must end with "/"
languageCode             = "en-us"
defaultContentLanguage   = "en"
isMultilingual           = false
title                    = "Julien Pelegri"
theme                    = "sam"
pygmentsStyle            = "monokai"                        # https://help.farbox.com/pygments.html
pygmentsCodefences       = true
# googleAnalytics        = ""                               # Tracking code, eg. "UA-111111111-1"

[params]
    dateform             = "Mon Jan 02, 2006"
    dateformfull         = "Mon Jan 2 2006 15:04:05 EST"
    favicon              = "sam.ico"
    homepage             = "main"                           # What to call the home page link
    footerText           = "© 2019 Julien Pelegri MIT"

# Metadata for Open Graph and Twitter
    description          = "Julien Pelegri Website"               # Max 160 characters show in search results
    images               = ["julien.png"]                       # Image that shows on Twitter cards and Open Graph links to the site
    title                = "Julien Pelegri"



[[params.mainMenu]]
    link = "/portfolio"
    text = "Portfolio"

[[params.mainMenu]]
    link = "/about"
    text = "Who am I?"



[imaging]
    quality = 75
